/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Admin_reservation: typeof import('./src/components/Modals/admin_reservation.vue')['default']
    Calendar: typeof import('./src/components/Calendar.vue')['default']
    Calendarmodal: typeof import('./src/components/Modals/Calendarmodal.vue')['default']
    Detail: typeof import('./src/components/Checklist/detail.vue')['default']
    Edit_course_modal: typeof import('./src/components/Modals/edit_course_modal.vue')['default']
    Edit_user_modal: typeof import('./src/components/Modals/edit_user_modal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowDetail: typeof import('./src/components/Modals/showDetail.vue')['default']
  }
}
